submit_donasi/urls.py
from django.urls import path
from . import views

app_name='submit_donasi'

urlpatterns=[
    # path('thankyou/', thankyou, name='thankyou'),
    path('submitdon/',views.showdonation, name='submitdon'),
    path('Add_Donation/',views.submitdon, name='Add_Donation'),
    path('thankyou/', views.showdonatur, name='thankyou'),
    # path('filledsub/', views.filledsub, name='filledsub'),
]

tp1/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.conf.urls import url,include
from homepage import urls as home
from category import urls as category
from about import urls as about
from login import urls as login_page
from signup import urls as signup_page
from history import urls as history
from submit_donasi import urls as submit_donasi

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('auth/', include('social_django.urls', namespace='social')),
    url('', include(home)),
	url('', include(category)),
    url('', include(about)),
    url('', include(login_page)),
    url('', include(history)),
    url('', include(signup_page)),
    url('',include(submit_donasi)),
]

submit_donasi/models.py
#from django.core.validators import validate_email
from django.db import models

# Create your models here.

class Donmodels (models.Model):
    title = models.TextField()
    name = models.TextField(max_length=10, default=None)
    email = models.EmailField(max_length=254, default='test@example.com',db_index=True)
    nominal = models.IntegerField()
    publishedname = models.TextField(max_length=3, default=None)

    def dict(self):
        return{
            "title":self.title,
            "nominal":self.nominal,
            "email":self.email
        }

submit_donasi/forms.py
from django import forms    
from .models import Donmodels

class donforms(forms.Form):
    doncategory = [
        ('korban gempa dan tsunami Palu','Bantu Korban Gempa dan Tsunami Palu'),
        ('korban gempa Lombok', 'Bantu Korban Gempa Lombok'),
        ('korban di Donggala','Bantu Korban Donggala'),
        ('Pak Amin','Bantu Pak Amin Lawan Tumor di Mulutnya'),
        ('Eza','Bantu Eza Agar dapat Melihat Kembali'),
        ('Rano','Bantu Rano dari Kakinya yang Putus'),
        ('1000 Tenda untuk Pengungsi Lombok','1000 Tenda untuk Pengungsi Lombok'),
        ('anak-anak Korban Tsunami Palu', 'Bantu Anak-anak Korban Tsunami Palu'),
        ('korban Bencana SulTeng', 'Untuk Korban Bencana SulTeng'),
        ('Jamilah', 'Bantu Sembuhkan Kanker Tiroid Jamilah'),
        ('operasi katarak gratis', 'Bantuan Operasi Katarak Gratis'),
        ('RS Apung untuk Timur Indonesia', 'RS Apung untuk Timur Indonesia'),
    ]

    donkepentingan =[
        ('yes','Donasi sebagai anonim'),
        ('no','Tulis nama saya'),
    ]

    # category = forms.CharField(label='Kategori', required=True, widget=forms.Select(choices=doncategory, attrs={'class' : 'form-control','placeholder': 'Pilih Kategori..', 'required': 'Harap diisi'}))
    title = forms.CharField(
        label='Nama Program', 
        required=True, 
        widget=forms.Select(choices=doncategory, 
        attrs={'class' : 'form-control','placeholder': 'Pilih Kategori..', 'required': 'Harap diisi'}))
    # nama = forms.CharField(
    #     label= 'Nama Lengkap', 
    #     required=True,  
    #     widget=forms.TextInput(attrs={'class' : 'form-control','placeholder': 'Tulis Nama..', 'required': 'Harap diisi'}))
    # email = forms.EmailField(
    #     label= 'Alamat Email', 
    #     required=True, 
    #     widget=forms.EmailInput({'class': 'form-control', 'placeholder': 'test@example.com', 'required': 'Harap diisi'}))
    nominal = forms.IntegerField(
        label='Nominal Donasi', 
        required=True,  
        widget=forms.NumberInput(attrs={'class' : 'form-control','placeholder': 'Tulis Nominal..', 'required': 'Harap diisi'}))
    publishedname = forms.ChoiceField(
        label='Apakah Anda ingin donasi anda sebagai anonim?', 
        required=True,
        choices=donkepentingan,
        widget=forms.RadioSelect())

submit_donasi/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import JsonResponse
# from django.utils.datastructures import MultiValueDictKeyError
# from django.contrib import messages
from .models import Donmodels
from .forms import donforms
from signup.models import Signup
from django.db import IntegrityError
from google.auth.transport import requests as requests2
from google.oauth2 import id_token


# Create your views here.

response = {}
def showdonation(request):
    form = donforms(request.POST)
    html = 'submit_donasi.html'
    return render(request,html,{'form':form})

# def submitdon(request):
#     # if request.user.is_authenticated:
#     #     request.session['username'] = request.user.username
#     #     request.session['email'] = request.user.email

#         response['form'] = donforms()
#         form = donforms(request.POST or None)
#         if(request.method == 'POST' and form.is_valid()):
#             email_utk_dicek = request.POST['email']
#             hasil = Signup.objects.filter(email = email_utk_dicek)
#             if(hasil != None):
#             # registered = Signup.objects.all()
#             # for member in registered:
#             #     if(member.email  request.POST['email']):
#                 response['title'] = request.POST['title']
#                 response['nama'] = request.POST['nama']
#                 response['email'] = request.POST['email']
#                 response['nominal'] = request.POST['nominal']
#                 response['publishedname'] = request.POST['publishedname']
#                 writedon = Donmodels(title=response['title'],nama=response['nama'], email=response['email'], nominal=response['nominal'], publishedname=response['publishedname'])
#                 writedon.save()
#                 response['status'] = 'valid'
#                 # list_donatur = Donmodels.objects.all()
#                 # response['list_donatur']=list_donatur
#                 # html = 'riwayat.html'
#                 # return render(request,html,response)
#                 # return HttpResponseRedirect('/riwayat/')
#             else:
#                 response['status'] = 'invalid'
#                 return render(request, 'submit_donasi.html', response)
#         html = 'riwayat.html'
#         return render(request,html,response)

def submitdon(request):
    if request.user.is_authenticated:
        request.session['username'] = request.user.username
        request.session['email'] = request.user.email
        # status = 'valid'

        response['form'] = donforms()
        if(request.method == 'POST'):
            response['name'] = request.session['username']
            response['email'] = request.session['email']
            response['title'] = request.POST['title']
            response['nominal'] = request.POST['nominal']
            response['publishedname'] = request.POST['publishedname']
            # try:
            writedon = Donmodels(name=response['name'], email= response['email'], title=response['title'], nominal=response['nominal'], publishedname=response['publishedname'])
            writedon.save()
            return HttpResponseRedirect('/thankyou/')
                # return JsonResponse({'stat': status})
            # except IntegrityError as e:
            #     # status = 'invalid'
            #     return HttpResponseRedirect('/login_post/')
            #     # return JsonResponse({'stat': status})
    else:
        # status = 'invalid'
        return HttpResponseRedirect('/login_post/')
        # return JsonResponse({'stat': status})
    
# def filledsub(request):
#     all_obj = Donmodels.objects.all().values()
#     filled = list(all_obj)
#     return JsonResponse(filled, safe= False)

def showdonatur(request):
    list_donatur = Donmodels.objects.all()
    response['list_donatur']=list_donatur
    return render(request, 'thankyou.html',response)

# def riwayat(request):
#     return render(request, 'riwayat.html', response)

# def showriwayat(request):
#     total = 0
#     email = request.session['email']
#     submitted = Donmodels.objects.filter(email=email)
#     arr = []
#     for i in submitted:
#         data = {}
#         data['titlesubmitted'] = i.title
#         data['nominalsubmitted'] = i.nominal
#         arr.append(data)
#         total += 'nominalsubmitted'
#     return JsonResponse(arr)

submit_donasi/templates/riwayat.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
    Riwayat
{% endblock title %}

{% block css %}
    <link rel="stylesheet" type= 'text/css' href="{% static 'css/styles.css' %}">
{% endblock css %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <!--col1-->
            </div>
            <div class="col">
                {% if user.is_authenticated %}
                    <h1>{{ user.username }}, Terima kasih atas segala sumbangsihmu.</h1>
                    <h2>Sejauh ini, Anda telah mendonasikan sebanyak {{ total }}. Berikut riwayat donasi Anda.<h2>
                {% endif %}
            </div>
            <div class="col">
                <!--col3-->
            </div>
        </div>

        <table class="table table-hover">
            <thead>
                <tr>
                <th scope="col">Program</th>
                <th scope="col">Nominal</th>
                </tr>
            </thead>
            <tbody id = 'tableBody'>
                {% for i in arr %}
                    <tr>
                        <td> {{ i.titlesubmitted }} </td>
                        <td> {{ i.nominalsubmitted }} </td>
                    </tr>
                {% endfor %}
            </tbody>
            </table>

    </div>
{% endblock %}

submit_donasi/templates/submit_donasi.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
    Donasi
{% endblock title %}

{% block css %}
    <style>
        #margintop{
            margin-top:100px;
        }
        .form-group {
            width: 50%;
        }

        .btn {
            background-color: #7fe9b7;
        }

        ul {
            list-style-type: none;
        }

        #bg { 
            /* The image used */
            background-image: url("https://i.imgur.com/zQi6bH1.jpg");

            /* Full height */
            height: 600px; 

            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            display: block;
        }
    </style>

    {% comment %} <link rel="stylesheet" type= 'text/css' href="{% static 'css/styles.css' %}"> {% endcomment %}
{% endblock css %}

{% block content %}
    <div class="container">
        <center>
        <h2 align='center'>Tunjukkan Empati, Bantu Sesama</h2>
        <h4 align='center'>Dimulai dari Sini.</h4>
        <br>
        <div id="alertField"></div>
        <br>
        <div></div>
        <div id="toHide"></div>
        <div class="form-group">
            <form id="form" method="POST" action="{%url 'submit_donasi:Add_Donation'%}">
                {% csrf_token %}
                {% for field in form %}
                <!-- {% csrf_token %} -->
                    {{ field.label_tag }}
                    <br>
                    {{ field }}
                {% endfor %}
                <div class="submit-btn">
                    <input id="submit" type="submit" class="btn" value="Submit">
                </div>
            </form>
        </div>
        </center>
    </div>
{% endblock %}

submit_donasi/templates/thankyou.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
    Laporan Pemasukan Donasi
{% endblock title %}

{% block css %}
    <style>
        #margintop{
            margin-top:100px;
        }
        .form-group {
            width: 50%;
        }

        .btn {
            background-color: #7fe9b7;
        }

        ul {
            list-style-type: none;
        }

        #bg { 
            /* The image used */
            background-image: url("https://i.imgur.com/zQi6bH1.jpg");

            /* Full height */
            height: 600px; 

            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            display: block;
        }
    </style>
    {% comment %} <link rel="stylesheet" type= 'text/css' href="{%static 'css/styles.css'%}"> {% endcomment %}
{% endblock css %}

    {% block content %}
    <div class="jumbotron">
            <h1 class="display-4">Laporan Total Pemasukan Donasi</h1>
            <p class="lead">Uluran tangan Anda sangat berarti bagi mereka.</p>
            <hr class="my-4">
            <p>Berikut rincian pemasukan donasi.</p>
            <!-- <button class="btn"><a href="{% url 'submit_donasi:submitdon' %}">Kembali ke Halaman Submit</button> -->
    </div>
    <div id="bg" class="jumbotron">
        <center>
        <table class="table table-dark">
            <thead>
                <tr>
                    <th>Pengirim</th>
                    <th>Penerima</th>
                    <th>Donasi sebesar</th>
                </tr>
            </thead>
            <tbody>
                {% for i in list_donatur %}
                <tr>
                    {% if i.publishedname == 'yes' %}
                        <td>Anonim</td>
                    {% else %}
                        <td> {{ i.name }} </td>
                    {% endif %}
                    <td> {{ i.title }} </td>
                    <td> {{ i.nominal }} </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </center>
    </div>
    {% endblock %}